# -*- coding: utf-8 -*-
"""AllCountryData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZM5sQ6aBuGSJdw1JrC7XBLxmNvb2a5M8
"""

# !pip install langdetect

# !pip install pathlib

import pandas as pd
from langdetect import detect
import glob
import os
from pathlib import Path
from collections import Counter

languageDictionary ={'el'    : 'Greek',
'eo'    : 'Esperanto',
'en'    : 'English',
'af'    : 'Afrikaans',
'sw'    : 'Swahili',
'ca'    : 'Catalan',
'it'    : 'Italian',
'sv'    : 'Swedish',
'cs'    : 'Czech',
'cy'    : 'Welsh',
'ar'    : 'Arabic',
'ur'   :  'Urdu',
'ga'    : 'Irish',
'eu'    : 'Basque',
'et'    : 'Estonian',
'az'    : 'Azerbaijani',
'id'    : 'Indonesian',
'es'    : 'Spanish',
'ru'    : 'Russian',
'gl'    : 'Galician',
'nl'    : 'Dutch',
'pt'    : 'Portuguese',
'la'    : 'Latin',
'tr'    : 'Turkish',
'tl'    : 'Filipino',
'lv'    : 'Latvian',
'lt'    : 'Lithuanian',
'th'    : 'Thai',
'vi'    : 'Vietnamese',
'gu'    : 'Gujarati',
'ro'    : 'Romanian',
'is'    : 'Icelandic',
'pl'    : 'Polish',
'ta'    : 'Tamil',
'yi'    : 'Yiddish',
'be'    : 'Belarusian',
'fr'    : 'French',
'bg'    : 'Bulgarian',
'uk'    : 'Ukrainian',
'hr'    : 'Croatian',
'bn'    : 'Bengali',
'sl'    : 'Slovenian',
'ht'    : 'Haitian Creole',
'da'    : 'Danish',
'fa'    : 'Persian',
'hi'    : 'Hindi',
'fi'    : 'Finnish',
'hu'    : 'Hungarian',
'ja'    : 'Japanese',
'ka'    : 'Georgian',
'te'    : 'Telugu',
'zh-tw' : 'Chinese Traditional',
'sq'    : 'Albanian',
'no'    : 'Norwegian',
'ko'    : 'Korean',
'kn'    : 'Kannada',
'mk'    : 'Macedonian',
'zh-cn' : 'Chinese Simplified',
'sk'    : 'Slovak',
'mt'    : 'Maltese',
'de'    : 'German',
'ms'    : 'Malay',
'sr'    : 'Serbian',
'so'    : 'Somali',
'he'    : 'Hebrew',
'ml'    : 'Malayalam',
'ne'    : 'Nepali',
'mr'    : 'Marathi',
'pa'    : 'Panjabi'
}

Folders = []
Folders = ['1USA','2India','3SouthKorea','4Japan','5UK','6Canada','7France','8Spain','9Argentina','10Australia','11Mexico','12Germany',
          '13Indonesia','14Italy','15Brazil','16Thailand','17Sweden','18Netherlands','19Pakistan','20SouthAfrica','21Nigeria','22Colombia',
          '23Ireland','24Finland','25Belgium','26Chile','27Philippines','28Turkey','29Switzerland','30Malaysia','31Russia','32Venezuela',
          '33NewZealand']

df_rows = []

 
for path in Path('1USA').iterdir():
	if path.name.endswith('Data'):
		for file in Path(path).iterdir():
			if file.name.endswith('.xls'):
				data = pd.read_excel(file, skiprows=[0])
				df_rows.append(data)

print('USA data is read')
df = pd.concat(df_rows, axis=0, ignore_index=True)

languages= []
contents = list(df['Contents'])
for content in contents:
        try:
            languages.append(detect(content))
        except Exception:
            languages.append(None)
        print(len(languages))

df['Language'] = languages

df['Language'] = df['Language'].replace(languageDictionary)

df.to_pickle('USAData.pkl')
df.to_excel('USAData.xlsx')
print('Data exported')